### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [turnerba/lights#71]
Hi Brady,
I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

Looking at your readme and your code (e.g.  lights.rb register_username method), it looks like this change will affect you. After February 2016, the setting of the username will not work so it should be removed, and the randomly generated username should be taken from the bridge success response (as shown in above link).  Apologies for the inconvenience caused.

Thanks
Steve

**Comment by turnerba** [comment]
Thank you @SteveyO! I will fix it right up. This is a good change, client generated usernames were unnecessary in my opinion.

**Comment by SteveyO** [comment]
Thanks great news.  Yes I agree,  it is a good change,  of course a little bit of an inconvenience for guys who have written Hue SDKs and Libraries but thanks for the understanding.
Steve

**Comment by turnerba** [comment]
Addressed in PR #73
